[package]
name = "rresolve"
version = "0.1.0"
authors = ["ty <ty@notarealemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
nom  = "6"
rand = "0.8"
